In [1]:
import os
import sys
os.environ["PYSPARK_PYTHON"] = "/home/ec2-user/spark-2.4.4-bin-hadoop2.7/python"
os.environ["JAVA_HOME"] = "/usr/java/jdk1.8.0_161/jre"
os.environ["SPARK_HOME"] = "/home/ec2-user/spark-2.4.4-bin-hadoop2.7"
os.environ["PYLIB"] = os.environ["SPARK_HOME"] + "/python/lib"
sys.path.insert(0, os.environ["PYLIB"] + "/py4j-0.10.7-src.zip")
sys.path.insert(0, os.environ["PYLIB"] + "/pyspark.zip")

In [2]:
from pyspark.sql import SparkSession

In [3]:
spark = SparkSession.builder.appName("IPL").getOrCreate()

In [4]:
ball = spark.read.csv("Ball_By_Ball.csv", inferSchema=True,header=True)

In [5]:
ball.show()

+--------+-------+-------+----------+------------+------------+------------------------+----------+-----------+----------+-----+-------+----+-------+-------+-------------+--------------+------+------+-------+---+------------+-------+-----------------+----------+----------------+-------------+----------+------+-------+-----------+------+----------+--------+----------------+---------+-------------------+-------------+----------------+----------+---------------+---------+------------------+--------------+--------------+------------+-------------+-----------+
|MatcH_id|Over_id|Ball_id|Innings_No|Team_Batting|Team_Bowling|Striker_Batting_Position|Extra_Type|Runs_Scored|Extra_runs|Wides|Legbyes|Byes|Noballs|Penalty|Bowler_Extras|      Out_type|Caught|Bowled|Run_out|LBW|Retired_hurt|Stumped|caught_and_bowled|hit_wicket|ObstructingFeild|Bowler_Wicket|Match_Date|Season|Striker|Non_Striker|Bowler|Player_Out|Fielders|Striker_match_SK|StrikerSK|NonStriker_match_SK|NONStriker_SK|Fielder_match_SK|Fielder_SK|Bowler_match_SK|BOWLER_SK|PlayerOut_match_SK|BattingTeam_SK|BowlingTeam_SK|Keeper_Catch|Player_out_sk|MatchDateSK|
+--------+-------+-------+----------+------------+------------+------------------------+----------+-----------+----------+-----+-------+----+-------+-------+-------------+--------------+------+------+-------+---+------------+-------+-----------------+----------+----------------+-------------+----------+------+-------+-----------+------+----------+--------+----------------+---------+-------------------+-------------+----------------+----------+---------------+---------+------------------+--------------+--------------+------------+-------------+-----------+
|  598028|     15|      6|         1|           5|           2|                       6| No Extras|          4|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    277|        104|    83|      null|    null|           20336|      276|              20333|          103|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      1|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      2|         1|           5|           2|                       3| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      3|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      4|         1|           5|           2|                       3| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      5|         1|           5|           2|                       3| No Extras|          4|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     14|      6|         1|           5|           2|                       3| No Extras|          2|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      1|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|    83|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      2|         1|           5|           2|                       3| No Extras|          4|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|    83|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      3|         1|           5|           2|                       3| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|    83|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      4|         1|           5|           2|                       5| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|    83|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      5|         1|           5|           2|                       5| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|    83|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     13|      6|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|    83|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      1|         1|           5|           2|                       3| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      2|         1|           5|           2|                       5| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      3|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      4|         1|           5|           2|                       3| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|      6|        104|   346|      null|    null|           20328|        5|              20333|          103|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      5|         1|           5|           2|                       5| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     12|      6|         1|           5|           2|                       5| No Extras|          1|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|   346|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20348|      345|                -1|             4|             1|           0|            0|   20130420|
|  598028|     11|      1|         1|           5|           2|                       5| No Extras|          0|         0|    0|      0|   0|      0|      0|            0|Not Applicable|     0|     0|      0|  0|           0|      0|                0|         0|               0|            0| 4/20/2013|  2013|    104|          6|    83|      null|    null|           20333|      103|              20328|            5|              -1|        -1|          20343|       82|                -1|             4|             1|           0|            0|   20130420|
+--------+-------+-------+----------+------------+------------+------------------------+----------+-----------+----------+-----+-------+----+-------+-------+-------------+--------------+------+------+-------+---+------------+-------+-----------------+----------+----------------+-------------+----------+------+-------+-----------+------+----------+--------+----------------+---------+-------------------+-------------+----------------+----------+---------------+---------+------------------+--------------+--------------+------------+-------------+-----------+
only showing top 20 rows

In [9]:
ball.columns

['MatcH_id',
 'Over_id',
 'Ball_id',
 'Innings_No',
 'Team_Batting',
 'Team_Bowling',
 'Striker_Batting_Position',
 'Extra_Type',
 'Runs_Scored',
 'Extra_runs',
 'Wides',
 'Legbyes',
 'Byes',
 'Noballs',
 'Penalty',
 'Bowler_Extras',
 'Out_type',
 'Caught',
 'Bowled',
 'Run_out',
 'LBW',
 'Retired_hurt',
 'Stumped',
 'caught_and_bowled',
 'hit_wicket',
 'ObstructingFeild',
 'Bowler_Wicket',
 'Match_Date',
 'Season',
 'Striker',
 'Non_Striker',
 'Bowler',
 'Player_Out',
 'Fielders',
 'Striker_match_SK',
 'StrikerSK',
 'NonStriker_match_SK',
 'NONStriker_SK',
 'Fielder_match_SK',
 'Fielder_SK',
 'Bowler_match_SK',
 'BOWLER_SK',
 'PlayerOut_match_SK',
 'BattingTeam_SK',
 'BowlingTeam_SK',
 'Keeper_Catch',
 'Player_out_sk',
 'MatchDateSK']

In [6]:
match = spark.read.csv("Match.csv",inferSchema=True, header=True)

In [8]:
match.show()

+--------+--------+--------------------+--------------------+----------+-----------+--------------------+----------+------------+--------------------+--------------------+---------+--------+------------+-------------+----------+----------+
|Match_SK|match_id|               Team1|               Team2|match_date|Season_Year|          Venue_Name| City_Name|Country_Name|         Toss_Winner|        match_winner|Toss_Name|Win_Type|Outcome_Type|    ManOfMach|Win_Margin|Country_id|
+--------+--------+--------------------+--------------------+----------+-----------+--------------------+----------+------------+--------------------+--------------------+---------+--------+------------+-------------+----------+----------+
|       0|  335987|Royal Challengers...|Kolkata Knight Ri...| 4/18/2008|       2008|M Chinnaswamy Sta...| Bangalore|       India|Royal Challengers...|Kolkata Knight Ri...|    field|    runs|      Result|  BB McCullum|       140|         1|
|       1|  335988|     Kings XI Punjab| Chennai Super Kings| 4/19/2008|       2008|Punjab Cricket As...|Chandigarh|       India| Chennai Super Kings| Chennai Super Kings|      bat|    runs|      Result|   MEK Hussey|        33|         1|
|       2|  335989|    Delhi Daredevils|    Rajasthan Royals| 4/19/2008|       2008|    Feroz Shah Kotla|     Delhi|       India|    Rajasthan Royals|    Delhi Daredevils|      bat| wickets|      Result|  MF Maharoof|         9|         1|
|       3|  335990|      Mumbai Indians|Royal Challengers...| 4/20/2008|       2008|    Wankhede Stadium|    Mumbai|       India|      Mumbai Indians|Royal Challengers...|      bat| wickets|      Result|   MV Boucher|         5|         1|
|       4|  335991|Kolkata Knight Ri...|     Deccan Chargers| 4/20/2008|       2008|        Eden Gardens|   Kolkata|       India|     Deccan Chargers|Kolkata Knight Ri...|      bat| wickets|      Result|    DJ Hussey|         5|         1|
|       5|  335992|    Rajasthan Royals|     Kings XI Punjab| 4/21/2008|       2008|Sawai Mansingh St...|    Jaipur|       India|     Kings XI Punjab|    Rajasthan Royals|      bat| wickets|      Result|    SR Watson|         6|         1|
|       6|  335993|     Deccan Chargers|    Delhi Daredevils| 4/22/2008|       2008|Rajiv Gandhi Inte...| Hyderabad|       India|     Deccan Chargers|    Delhi Daredevils|      bat| wickets|      Result|     V Sehwag|         9|         1|
|       7|  335994| Chennai Super Kings|      Mumbai Indians| 4/23/2008|       2008|MA Chidambaram St...|   Chennai|       India|      Mumbai Indians| Chennai Super Kings|    field|    runs|      Result|    ML Hayden|         6|         1|
|       8|  335995|     Deccan Chargers|    Rajasthan Royals| 4/24/2008|       2008|Rajiv Gandhi Inte...| Hyderabad|       India|    Rajasthan Royals|    Rajasthan Royals|    field| wickets|      Result|    YK Pathan|         3|         1|
|       9|  335996|     Kings XI Punjab|      Mumbai Indians| 4/25/2008|       2008|Punjab Cricket As...|Chandigarh|       India|      Mumbai Indians|     Kings XI Punjab|    field|    runs|      Result|KC Sangakkara|        66|         1|
|      10|  335997|Royal Challengers...|    Rajasthan Royals| 4/26/2008|       2008|M Chinnaswamy Sta...| Bangalore|       India|    Rajasthan Royals|    Rajasthan Royals|    field| wickets|      Result|    SR Watson|         7|         1|
|      11|  335998| Chennai Super Kings|Kolkata Knight Ri...| 4/26/2008|       2008|MA Chidambaram St...|   Chennai|       India|Kolkata Knight Ri...| Chennai Super Kings|      bat| wickets|      Result|     JDP Oram|         9|         1|
|      12|  335999|      Mumbai Indians|     Deccan Chargers| 4/27/2008|       2008|Dr DY Patil Sport...|    Mumbai|       India|     Deccan Chargers|     Deccan Chargers|    field| wickets|      Result| AC Gilchrist|        10|         1|
|      13|  336000|     Kings XI Punjab|    Delhi Daredevils| 4/27/2008|       2008|Punjab Cricket As...|Chandigarh|       India|    Delhi Daredevils|     Kings XI Punjab|      bat| wickets|      Result|    SM Katich|         4|         1|
|      14|  336001|Royal Challengers...| Chennai Super Kings| 4/28/2008|       2008|M Chinnaswamy Sta...| Bangalore|       India| Chennai Super Kings| Chennai Super Kings|      bat|    runs|      Result|     MS Dhoni|        13|         1|
|      15|  336002|Kolkata Knight Ri...|      Mumbai Indians| 4/29/2008|       2008|        Eden Gardens|   Kolkata|       India|Kolkata Knight Ri...|      Mumbai Indians|      bat| wickets|      Result|ST Jayasuriya|         7|         1|
|      16|  336003|    Delhi Daredevils|Royal Challengers...| 4/30/2008|       2008|    Feroz Shah Kotla|     Delhi|       India|Royal Challengers...|    Delhi Daredevils|    field|    runs|      Result|   GD McGrath|        10|         1|
|      17|  336004|     Deccan Chargers|     Kings XI Punjab|  5/1/2008|       2008|Rajiv Gandhi Inte...| Hyderabad|       India|     Kings XI Punjab|     Kings XI Punjab|    field| wickets|      Result|     SE Marsh|         7|         1|
|      18|  336005|    Rajasthan Royals|Kolkata Knight Ri...|  5/1/2008|       2008|Sawai Mansingh St...|    Jaipur|       India|    Rajasthan Royals|    Rajasthan Royals|      bat|    runs|      Result|  SA Asnodkar|        45|         1|
|      19|  336006| Chennai Super Kings|    Delhi Daredevils|  5/2/2008|       2008|MA Chidambaram St...|   Chennai|       India| Chennai Super Kings|    Delhi Daredevils|      bat| wickets|      Result|     V Sehwag|         8|         1|
+--------+--------+--------------------+--------------------+----------+-----------+--------------------+----------+------------+--------------------+--------------------+---------+--------+------------+-------------+----------+----------+
only showing top 20 rows

In [12]:
match.columns

['Match_SK',
 'match_id',
 'Team1',
 'Team2',
 'match_date',
 'Season_Year',
 'Venue_Name',
 'City_Name',
 'Country_Name',
 'Toss_Winner',
 'match_winner',
 'Toss_Name',
 'Win_Type',
 'Outcome_Type',
 'ManOfMach',
 'Win_Margin',
 'Country_id']

## Task 

#### Find the number of 6s hit in Wankhede stadium
#### Find Highest score made to which venue

#### The data has lot of columns. Instead of carring all the columns lets select the relevant columns to solve the problem

In [10]:
ball_subset = ball.select(['MatcH_id','Runs_Scored'])

In [21]:
ball_subset.count()

150451

In [11]:
ball_subset.show()

+--------+-----------+
|MatcH_id|Runs_Scored|
+--------+-----------+
|  598028|          4|
|  598028|          1|
|  598028|          1|
|  598028|          1|
|  598028|          0|
|  598028|          4|
|  598028|          2|
|  598028|          1|
|  598028|          4|
|  598028|          1|
|  598028|          0|
|  598028|          0|
|  598028|          1|
|  598028|          1|
|  598028|          0|
|  598028|          1|
|  598028|          1|
|  598028|          0|
|  598028|          1|
|  598028|          0|
+--------+-----------+
only showing top 20 rows

In [13]:
match_subset = match.select(['match_id','Venue_Name'])

In [20]:
match_subset.count()

637

In [14]:
match_subset.show()

+--------+--------------------+
|match_id|          Venue_Name|
+--------+--------------------+
|  335987|M Chinnaswamy Sta...|
|  335988|Punjab Cricket As...|
|  335989|    Feroz Shah Kotla|
|  335990|    Wankhede Stadium|
|  335991|        Eden Gardens|
|  335992|Sawai Mansingh St...|
|  335993|Rajiv Gandhi Inte...|
|  335994|MA Chidambaram St...|
|  335995|Rajiv Gandhi Inte...|
|  335996|Punjab Cricket As...|
|  335997|M Chinnaswamy Sta...|
|  335998|MA Chidambaram St...|
|  335999|Dr DY Patil Sport...|
|  336000|Punjab Cricket As...|
|  336001|M Chinnaswamy Sta...|
|  336002|        Eden Gardens|
|  336003|    Feroz Shah Kotla|
|  336004|Rajiv Gandhi Inte...|
|  336005|Sawai Mansingh St...|
|  336006|MA Chidambaram St...|
+--------+--------------------+
only showing top 20 rows

In [15]:
ball_subset.createTempView("ball_table")

In [16]:
match_subset.createTempView("match_table")

In [17]:
df_joined = spark.sql("select match_table.Venue_Name, ball_table.Runs_Scored from ball_table left join match_table on ball_table.MatcH_id == match_table.match_id ")

In [18]:
df_joined.collect()

[Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=4),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=4),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=2),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=4),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=4),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=1),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='M Chinnaswamy Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=3),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=2),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=2),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=2),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=2),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=6),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=2),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=1),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=4),
 Row(Venue_Name='Sawai Mansingh Stadium', Runs_Scored=0),
 Row(Venue_Name='MA Chidambaram Stadium, Chepauk', Runs_Scored=0),
 Row(Venue_Name='MA Chidambaram Stadium, Chepauk', Runs_Scored=1),
 Row(Venue_Name='MA Chidambaram Stadium, Chepauk', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=6),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=6),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=2),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=0),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=6),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=4),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=6),
 Row(Venue_Name='Feroz Shah Kotla', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=6),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=6),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=6),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=6),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=0),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=4),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=2),
 Row(Venue_Name='Brabourne Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=4),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=4),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=2),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=4),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=6),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=4),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=1),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=4),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=0),
 Row(Venue_Name='Wankhede Stadium', Runs_Scored=6),

In [22]:
df_joined.createTempView("score_venue_data")

In [25]:
spark.sql("select * from score_venue_data where Venue_Name=='Wankhede Stadium' and Runs_Scored==6").count()

656

In [26]:
spark.sql("select Venue_Name, sum(Runs_Scored) as total_score from score_venue_data group by Venue_Name").show()

+--------------------+-----------+
|          Venue_Name|total_score|
+--------------------+-----------+
|Dubai Internation...|       1942|
|Himachal Pradesh ...|       2716|
|Sardar Patel Stad...|       3589|
|Punjab Cricket As...|      10421|
|    Barabati Stadium|       2195|
|Punjab Cricket As...|       1184|
|Punjab Cricket As...|       2232|
|Rajiv Gandhi Inte...|       2419|
|       Nehru Stadium|       1286|
|Maharashtra Crick...|       4538|
|        Eden Gardens|      17105|
|     OUTsurance Oval|        484|
|M Chinnaswamy Sta...|      19423|
|    Feroz Shah Kotla|      17491|
|Rajiv Gandhi Inte...|      11748|
|   Brabourne Stadium|       3595|
|Vidarbha Cricket ...|        822|
|          Green Park|       1236|
|Holkar Cricket St...|       1487|
|Shaheed Veer Nara...|       1664|
+--------------------+-----------+
only showing top 20 rows

In [27]:
spark.sql("select Venue_Name, sum(Runs_Scored) as total_score from score_venue_data group by Venue_Name").collect()

[Row(Venue_Name='Dubai International Cricket Stadium', total_score=1942),
 Row(Venue_Name='Himachal Pradesh Cricket Association Stadium', total_score=2716),
 Row(Venue_Name='Sardar Patel Stadium, Motera', total_score=3589),
 Row(Venue_Name='Punjab Cricket Association Stadium, Mohali', total_score=10421),
 Row(Venue_Name='Barabati Stadium', total_score=2195),
 Row(Venue_Name='Punjab Cricket Association IS Bindra Stadium Mohali', total_score=1184),
 Row(Venue_Name='Punjab Cricket Association IS Bindra Stadium, Mohali', total_score=2232),
 Row(Venue_Name='Rajiv Gandhi International Stadium Uppal', total_score=2419),
 Row(Venue_Name='Nehru Stadium', total_score=1286),
 Row(Venue_Name='Maharashtra Cricket Association Stadium', total_score=4538),
 Row(Venue_Name='Eden Gardens', total_score=17105),
 Row(Venue_Name='OUTsurance Oval', total_score=484),
 Row(Venue_Name='M Chinnaswamy Stadium', total_score=19423),
 Row(Venue_Name='Feroz Shah Kotla', total_score=17491),
 Row(Venue_Name='Rajiv Gandhi International Stadium, Uppal', total_score=11748),
 Row(Venue_Name='Brabourne Stadium', total_score=3595),
 Row(Venue_Name='Vidarbha Cricket Association Stadium, Jamtha', total_score=822),
 Row(Venue_Name='Green Park', total_score=1236),
 Row(Venue_Name='Holkar Cricket Stadium', total_score=1487),
 Row(Venue_Name='Shaheed Veer Narayan Singh International Stadium', total_score=1664),
 Row(Venue_Name='Sharjah Cricket Stadium', total_score=1728),
 Row(Venue_Name='Sheikh Zayed Stadium', total_score=1833),
 Row(Venue_Name="St George's Park", total_score=1904),
 Row(Venue_Name='Wankhede Stadium', total_score=16996),
 Row(Venue_Name='Newlands', total_score=1684),
 Row(Venue_Name='JSCA International Stadium Complex', total_score=1956),
 Row(Venue_Name='Saurashtra Cricket Association Stadium', total_score=3198),
 Row(Venue_Name='Dr DY Patil Sports Academy', total_score=4490),
 Row(Venue_Name='Buffalo Park', total_score=742),
 Row(Venue_Name='New Wanderers Stadium', total_score=2184),
 Row(Venue_Name='SuperSport Park', total_score=3440),
 Row(Venue_Name='Sawai Mansingh Stadium', total_score=9231),
 Row(Venue_Name='Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', total_score=2995),
 Row(Venue_Name='MA Chidambaram Stadium, Chepauk', total_score=14471),
 Row(Venue_Name='De Beers Diamond Oval', total_score=858),
 Row(Venue_Name='Kingsmead', total_score=4076),
 Row(Venue_Name='Subrata Roy Sahara Stadium', total_score=4518)]

In [28]:
df_venue_score = spark.sql("select Venue_Name, sum(Runs_Scored) as total_score from score_venue_data group by Venue_Name")

In [29]:
df_venue_score.show()

+--------------------+-----------+
|          Venue_Name|total_score|
+--------------------+-----------+
|Dubai Internation...|       1942|
|Himachal Pradesh ...|       2716|
|Sardar Patel Stad...|       3589|
|Punjab Cricket As...|      10421|
|    Barabati Stadium|       2195|
|Punjab Cricket As...|       1184|
|Punjab Cricket As...|       2232|
|Rajiv Gandhi Inte...|       2419|
|       Nehru Stadium|       1286|
|Maharashtra Crick...|       4538|
|        Eden Gardens|      17105|
|     OUTsurance Oval|        484|
|M Chinnaswamy Sta...|      19423|
|    Feroz Shah Kotla|      17491|
|Rajiv Gandhi Inte...|      11748|
|   Brabourne Stadium|       3595|
|Vidarbha Cricket ...|        822|
|          Green Park|       1236|
|Holkar Cricket St...|       1487|
|Shaheed Veer Nara...|       1664|
+--------------------+-----------+
only showing top 20 rows

In [30]:
df_venue_score.createTempView("venue_score_table")

In [31]:
spark.sql("select * from venue_score_table order by total_score desc").show()

+--------------------+-----------+
|          Venue_Name|total_score|
+--------------------+-----------+
|M Chinnaswamy Sta...|      19423|
|    Feroz Shah Kotla|      17491|
|        Eden Gardens|      17105|
|    Wankhede Stadium|      16996|
|MA Chidambaram St...|      14471|
|Rajiv Gandhi Inte...|      11748|
|Punjab Cricket As...|      10421|
|Sawai Mansingh St...|       9231|
|Maharashtra Crick...|       4538|
|Subrata Roy Sahar...|       4518|
|Dr DY Patil Sport...|       4490|
|           Kingsmead|       4076|
|   Brabourne Stadium|       3595|
|Sardar Patel Stad...|       3589|
|     SuperSport Park|       3440|
|Saurashtra Cricke...|       3198|
|Dr. Y.S. Rajasekh...|       2995|
|Himachal Pradesh ...|       2716|
|Rajiv Gandhi Inte...|       2419|
|Punjab Cricket As...|       2232|
+--------------------+-----------+
only showing top 20 rows